Update dependency org.springframework:spring-framework-bom to v6.2.4 (#88)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[org.springframework:spring-framework-bom](https://redirect.github.com/spring-projects/spring-framework)
| `6.2.3` -> `6.2.4` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/org.springframework:spring-framework-bom/6.2.4?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.springframework:spring-framework-bom/6.2.4?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.springframework:spring-framework-bom/6.2.3/6.2.4?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.springframework:spring-framework-bom/6.2.3/6.2.4?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>spring-projects/spring-framework
(org.springframework:spring-framework-bom)</summary>

###
[`v6.2.4`](https://redirect.github.com/spring-projects/spring-framework/releases/tag/v6.2.4)

#### :star: New Features

- JettyCoreHttpHandlerAdapter compatibility with Jetty 12.0.17
[#&#8203;34561](https://redirect.github.com/spring-projects/spring-framework/issues/34561)
- HandlerMethodValidationException.Visitor should support RequestBody
with method parameter constraints
[#&#8203;34549](https://redirect.github.com/spring-projects/spring-framework/issues/34549)
- Allow `ContentResultMatchersDsl` matchers for supertypes of the
checked type
[#&#8203;34542](https://redirect.github.com/spring-projects/spring-framework/pull/34542)
- Avoid `JarURLConnection` resource leak in
`AbstractFileResolvingResource.exists()`
[#&#8203;34528](https://redirect.github.com/spring-projects/spring-framework/issues/34528)
- Deprecate `rowsExpected` property of `SqlQuery` for removal
[#&#8203;34526](https://redirect.github.com/spring-projects/spring-framework/pull/34526)
- Supply `RuntimeHints` to an `AotContextLoader`
[#&#8203;34513](https://redirect.github.com/spring-projects/spring-framework/issues/34513)
- Deprecate and remove use of UrlPathHelper in
ServletWebSocketHandlerRegistry
[#&#8203;34508](https://redirect.github.com/spring-projects/spring-framework/issues/34508)
- Avoid unnecessary CGLIB processing on configuration classes
[#&#8203;34486](https://redirect.github.com/spring-projects/spring-framework/issues/34486)
- Inconsistent default class loaders in hint classes
[#&#8203;34470](https://redirect.github.com/spring-projects/spring-framework/issues/34470)
- Add missing converters to `DefaultRestClientBuilder`
[#&#8203;34439](https://redirect.github.com/spring-projects/spring-framework/issues/34439)
- Improve `BeanFactory`/`ObjectProvider` to select the only one default
candidate among non-default candidates
[#&#8203;34432](https://redirect.github.com/spring-projects/spring-framework/issues/34432)

#### :lady_beetle: Bug Fixes

- `MockCookie.parse()` fails to parse custom attribute with a value
[#&#8203;34575](https://redirect.github.com/spring-projects/spring-framework/issues/34575)
- `BeanNotOfRequiredTypeException` if `@Bean` factory method returns
`null`
[#&#8203;34543](https://redirect.github.com/spring-projects/spring-framework/issues/34543)
- Regression in 6.2.3: No unique bean available for injection point with
unresolvable generics
[#&#8203;34541](https://redirect.github.com/spring-projects/spring-framework/issues/34541)
- GenericConversionService cannot find a converter when converting to a
Kotlin list of maps
[#&#8203;34535](https://redirect.github.com/spring-projects/spring-framework/issues/34535)
- isClientDisconnectedException needs to protect against null input
[#&#8203;34533](https://redirect.github.com/spring-projects/spring-framework/issues/34533)
- spring boot 3.4.3 + TimedAspect causes thread to hang
[#&#8203;34522](https://redirect.github.com/spring-projects/spring-framework/issues/34522)
- Missing Partitioned cookie support in reactive HTTP clients
[#&#8203;34521](https://redirect.github.com/spring-projects/spring-framework/pull/34521)
- DefaultManagedTaskExecutor throws
java.lang.UnsupportedOperationException: isShutdown when rejecting tasks
[#&#8203;34514](https://redirect.github.com/spring-projects/spring-framework/issues/34514)
- FileSystemResource location does not end with slash for RouterFunction
check
[#&#8203;34509](https://redirect.github.com/spring-projects/spring-framework/issues/34509)
- AbstractJackson2HttpMessageConverter not resolving generic type for
request body since 6.2.3
[#&#8203;34504](https://redirect.github.com/spring-projects/spring-framework/issues/34504)
- Request param handling in HttpRequestValues overrides existing URI
variables with same name
[#&#8203;34499](https://redirect.github.com/spring-projects/spring-framework/issues/34499)
- MockHttpServletResponse - handle multiple values for Content-Language
header
[#&#8203;34488](https://redirect.github.com/spring-projects/spring-framework/issues/34488)
- Endless loop with DataSourceUtils in spring-jdbc
[#&#8203;34484](https://redirect.github.com/spring-projects/spring-framework/issues/34484)
- MockHttpServletResponse#setHeader does not remove header for null
values
[#&#8203;34464](https://redirect.github.com/spring-projects/spring-framework/issues/34464)
- ContentCachingResponseWrapper.setHeader does not handle null value
properly.
[#&#8203;34460](https://redirect.github.com/spring-projects/spring-framework/issues/34460)
- Component scan fails to find bean candidates in the embedded jar file
in META-INF/context.xml for embedded Tomcat application
[#&#8203;34446](https://redirect.github.com/spring-projects/spring-framework/issues/34446)
- 6.2.0 broke with "Could not register object \[`@someHash`] under bean
name 'blabla': there is already object \[`@sameHash`] bound"
[#&#8203;34427](https://redirect.github.com/spring-projects/spring-framework/issues/34427)
- 503 status code after completing SseEmitter in onTimeout
[#&#8203;34426](https://redirect.github.com/spring-projects/spring-framework/issues/34426)
- `NullPointerException` thrown when `ConfigurationClassEnhancer`
creates CGLIB proxy
[#&#8203;34423](https://redirect.github.com/spring-projects/spring-framework/issues/34423)
- Add onRequest() hook for propagating request from downstream
[#&#8203;34388](https://redirect.github.com/spring-projects/spring-framework/pull/34388)
- Content-Type response header duplicated for failed
StreamingResponseBody return value
[#&#8203;34366](https://redirect.github.com/spring-projects/spring-framework/issues/34366)
- Task scheduler configured by XML is not eligible for getting processed
by all BeanPostProcessors
[#&#8203;34015](https://redirect.github.com/spring-projects/spring-framework/issues/34015)

#### :notebook_with_decorative_cover: Documentation

- Fix typo in Spring MVC error responses documentation
[#&#8203;34552](https://redirect.github.com/spring-projects/spring-framework/pull/34552)
- Document that Spring Framework 6.x does not yet support JSpecify
annotations
[#&#8203;34551](https://redirect.github.com/spring-projects/spring-framework/issues/34551)
- Fix web and webflux reference links
[#&#8203;34517](https://redirect.github.com/spring-projects/spring-framework/pull/34517)
- Document default KeyGenerator in spring-cache XSD
[#&#8203;34468](https://redirect.github.com/spring-projects/spring-framework/pull/34468)
- Fix broken antora task
[#&#8203;34454](https://redirect.github.com/spring-projects/spring-framework/issues/34454)
- Add `@since` tag for formField() and formFields in
MockHttpServletRequestDsl
[#&#8203;34448](https://redirect.github.com/spring-projects/spring-framework/pull/34448)
- Improve Javadoc of ObjectProvider to clarify what is unique
[#&#8203;34447](https://redirect.github.com/spring-projects/spring-framework/pull/34447)
- rest-http-interface example code can't run
[#&#8203;34443](https://redirect.github.com/spring-projects/spring-framework/issues/34443)
- Add Javadoc since for HandlerMethod(HandlerMethod, Object, boolean)
[#&#8203;34431](https://redirect.github.com/spring-projects/spring-framework/pull/34431)
- Document wrapping behavior of `TestExecutionListener` callbacks
[#&#8203;34422](https://redirect.github.com/spring-projects/spring-framework/issues/34422)
- Cross reference annotation search APIs in Javadoc
[#&#8203;34421](https://redirect.github.com/spring-projects/spring-framework/issues/34421)

#### :hammer: Dependency Upgrades

- Upgrade to Micrometer 1.14.5
[#&#8203;34580](https://redirect.github.com/spring-projects/spring-framework/issues/34580)
- Upgrade to Reactor 2024.0.4
[#&#8203;34578](https://redirect.github.com/spring-projects/spring-framework/issues/34578)

#### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;chenggangpro](https://redirect.github.com/chenggangpro),
[@&#8203;dark2momo](https://redirect.github.com/dark2momo),
[@&#8203;dmitrysulman](https://redirect.github.com/dmitrysulman),
[@&#8203;izeye](https://redirect.github.com/izeye),
[@&#8203;ngocnhan-tran1996](https://redirect.github.com/ngocnhan-tran1996),
[@&#8203;pankratz76](https://redirect.github.com/pankratz76),
[@&#8203;quaff](https://redirect.github.com/quaff),
[@&#8203;ryanprayogo](https://redirect.github.com/ryanprayogo), and
[@&#8203;vpavic](https://redirect.github.com/vpavic)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/kpavlov/ai-mocks).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4yMDAuMCIsInVwZGF0ZWRJblZlciI6IjM5LjIwNy4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>